name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Build project bundle
        run: |
          cd gh-pages-dist
          npm i
          npx webpack

      - name: List files in ../docs directory before deploy
        run: |
          ls -la ../docs

      - name: List files in /docs directory before deploy
        run: |
          ls -la /docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../docs
